### ISSUE TITLE
Don't work for 939

### ISSUE THREAD

**Issue by coco9515** [AlmightyLks/SCPLockdown#1]
I tried the plugin on my test server, it works as intented for all SCPs except the 939.
I did not edit the config.

If that ever change anything; I roundlock the game as I'm alone, forcestart and change to 939.

**Comment by AlmightyLks** [comment]
![image](https://user-images.githubusercontent.com/54688434/96345278-b7d30500-109a-11eb-8fc6-aee6b4d4c502.png)  
Are you sure that you checked those two upper-floor doors?
The dogs are supposed to be able to get into the "hallway", but yet not outside of that - As a protection of players shooting them from above.

**Comment by coco9515** [comment]
I opened both the lower and upper doors; and even the 2 doors that exit the rooms.

**Comment by AlmightyLks** [comment]
Mind dm'ing me on Discord, so we can work this out together?

**Comment by AlmightyLks** [comment]
No elaboration on solving the issue.
